### PR TITLE
Simplify binary search using recursion.

### PR DESCRIPTION
**Pull request by kareman**
Surprisingly, this is also faster in the performance tests.

### CODE REVIEW

**Comment by ole** [comment]
Thanks! Please give me some time to review this. I'm quite busy this week.

**Comment by ole** [comment]
Sorry I haven't gotten to this yet. Did you happen to test the performance with an array of objects? I came across [this note on the Swift forums](https://forums.swift.org/t/revisiting-the-choice-of-sort-algorithm/8958) regarding recursion and performance:

> The current `sort` is problematic because it uses recursion heavily, which defeats a number of optimizations **relating to ARC** and elimination of the overhead of passing in a closure for the comparative for the comparator.

It would be interesting to check if there are significant performance differences between recursion and non-recursion when ARC is involved.

**Comment by kareman** [comment]
Good point, I added some unit tests for objects, plus some tests with arrays without duplicate values, and a scheme for performance testing release builds. On my computer I get between 30 and 70% improvement in the performance tests with recursion, also when using objects. Could the compiler be optimising away the recursion?

Also, do you know if the sorted array is able to use generic specialisation with the class I created in the unit tests? Do we need to include SortedArray.swift in the unit test module to get more real-life performance testing?

**Comment by ole** [comment]
Thank you! To be honest, I'm still extremely puzzled why recursion is faster.

> Also, do you know if the sorted array is able to use generic specialisation with the class I created in the unit tests? Do we need to include SortedArray.swift in the unit test module to get more real-life performance testing?

This is a good point. As far as I know, not even importing with `@testable` (which we don't do) would enable generics specialization for the `SortedArray` type within the test module. Whether including the file directly would be "more real-life" depends on your perspective. If clients add the file directly into their project, then yes, otherwise no.

Frankly, I don't care enough either way.

**Comment by ole** [comment]
I released [version 0.7.0](https://github.com/ole/SortedArray/releases/tag/0.7.0) that includes these changes.

**Pull request merged**
