### PR TITLE
Disable code coverage in schemes

### LINKED ISSUE #14: Invalid Bundle - Disallowed LLVM instrumentation
Apple has a new automatic check when validating the binary that was built using Xcode 9 / iOS 11 SDK. If the binary contains some code coverage instrumentation, it will be rejected. The full message is:

> Invalid Bundle - Disallowed LLVM instrumentation. Do not submit apps with
> LLVM profiling instrumentation or coverage collection enabled. Turn off
> LLVM profiling or code coverage, rebuild your app and resubmit the app.

### PR DESCRIPTION
**Pull request by plu**
Fix #14

### CODE REVIEW

**Comment by ole** [comment]
I was not aware of this, so thanks! To be honest, I'm hesitating to merge this because (a) it sucks to not have code coverage data and (b) I don't understand why a setting **for the Test action** should have any influence on a release build for the App Store.

@plu Do you by any chance have further information or a link where I could learn more about this issue? I will of course accept this if there is no other way to make this App-Store-compliant, but the prospect of maintaining separate schemes just for testing with code coverage is not very pleasant.

**Comment by plu** [comment]
@ole I don’t have any more details. But I tried another TestFlight upload today with this patch applied to this repo and three other dependencies, and it passed the automatic validation process.

The initial clue I found here: https://twitter.com/NeoNacho/status/908000986052128768

Maybe @neonichu knows more?

I understand that two schemes is no good solution. Also turning it off and keeping one scheme is bad. A command line flag for xcodebuild would be great.

**Comment by ole** [comment]
@plu Sorry I let this slip for so long. Did you see this using Carthage? If so, it seems that the Carthage 0.26 should have fixed this problem (see https://github.com/Carthage/Carthage/pull/2158).

From what I've read (e.g. https://developer.apple.com/library/content/qa/qa1964/_index.html), Xcode should be smart enough to do the right thing for Archive builds, but that didn't work with Carthage (before 0.26) because Carthage builds frameworks separately.

**Comment by plu** [comment]
Yep, using Carthage! I'll try to update to 0.26 soon. Thanks for the hint!

**Comment by plu** [comment]
I can confirm that this issue was fixed after I have updated Carthage to the latest version (0.26.2). Thanks!

**Comment by ole** [comment]
Awesome, thanks!

**Pull request closed without merging**
