### PR TITLE
Swift 4.2

### PR DESCRIPTION
**Pull request by klaaspieter**
Fixed all Swift 4.2 build errors and warnings. More info in the individual commits.

### CODE REVIEW

**Comment by klaaspieter** [comment]
It looks like I might have to do some work to make this compatible with older versions. 

I personally don't mind it if libraries drop support for libraries, especially if they make it clear which library versions support which Swift versions ([Argo] for example). I tend to upgrade quickly though so I might be biased.

[Argo]: https://github.com/thoughtbot/argo#version-compatibility

**Comment by ole** [comment]
@klaaspieter First of all, many thanks for working on this! I generally think that fixing deprecation warnings should not be the main motivation for dropping support for older Swift 3 versions. So far, I've consciously kept `.characters` etc. because it wasn't a big deal, and I continue to think that.

But I haven't yet looked at your changes in detail, I'll have to do that later. Being able to integrate #20 (which relies on SwiftPM features in Swift 4) would be a nice bonus.

**Comment by klaaspieter** [comment]
I took another look and am unsure how to continue. It looks like `.characters` is only used in the test suite, leaving it in there means those deprecation warnings will be part of the test suite. I tend to treat warnings as errors and thus want to fixed them. I thought about using `#if swift(<4)` but language checks only support `>=`. Which means we'll have to do:

```swift
#if swift(>=4.2) {
  // nothing? duplicate tests?
} else {
  // test that use `.characters`
}
```

I run into a similar problem with the `CountableRange` and `CountableClosedRange`. In Swift 4.2 these are `typealias` of `Range` and `ClosedRange`. In other words the methods that use them can only exist when Swift <= 4.2. Which would lead to:

```swift
#if swift(>=4.2) {
  // nothing. The functions already exist because their arguments are typealiases.
} else {
  func removeSubrange(_ bounds: CountableRange<Int>) {}
  func removeSubrange(_ bounds: CountableClosedRange<Int>) {}
}
```

I think it's weird to have a `if #swift` block that's empty, but I don't think there is another option. I don't have a lot of experience with backward compatibility frameworks though; it's likely I'm missing something.

Let me know how you want to move forward.

**Comment by ole** [comment]
I'm looking at this now.

> I think it's weird to have a if #swift block that's empty, but I don't think there is another option.

You can negate the conditions, so this seems to work:

    #if !swift(>=4.1.50) && (!swift(>=3.4) || swift(>=4.0))
    public mutating func removeSubrange(_ bounds: CountableRange<Int>) {
        _elements.removeSubrange(bounds)
    }

    public mutating func removeSubrange(_ bounds: CountableClosedRange<Int>) {
        _elements.removeSubrange(bounds)
    }
    #endif

I agree that it isn't pretty though.

**Comment by ole** [comment]
@klaaspieter I opened a new PR #24 that incorporates some of your fixes, but now e.g. the deletion of the removeSubrange methods – I fixed those using conditional compilation. You also convinced me to drop Swift 3 support. The new baseline is Swift 4.0.

I then made some more changes and did some cleanup. What do you think?

**Comment by ole** [comment]
@klaaspieter Ah, I forgot: once again, thank you very much for your contributions!

**Pull request closed without merging**
